### ISSUE TITLE
xls_workbook.name_map does not contain static values

### ISSUE THREAD

**Issue by stevengoossensB** [DissectMalware/XLMMacroDeobfuscator#66]
The xls_workbook.name_map contains the names for all values that are set when loading the document. However, only when the Operand type is oREF, the value is parsed correctly. I suppose this is an issue in the xlrd2 library already. Newer malware samples use these static defined values as a parameter for the execution of the macro (e.g. as a counter for a while loop).

![image](https://user-images.githubusercontent.com/10197869/101954711-dbc74880-3bfc-11eb-80e2-7dc004acaf54.png)
![image](https://user-images.githubusercontent.com/10197869/101954970-49737480-3bfd-11eb-976d-7dfe2c4df550.png)

E.g. Sample:
d6063921e36b12414d769eda7cf5715541d149e54168128ceeb800a05f9f2b3d
582e03fefa4da38ecedd2afc3625ed152f98854c986d95ca9b0aca8b7a3d260f

**Comment by DissectMalware** [comment]
This is fixed in the latest version of the xlmdeobfuscator and xlrd2.

Mainly in https://github.com/DissectMalware/XLMMacroDeobfuscator/commit/2d19c5561eb809e8d1ea90846b4777c396c65ef6

d6063921e36b12414d769eda7cf5715541d149e54168128ceeb800a05f9f2b3d:

![image](https://user-images.githubusercontent.com/9646319/105793866-e6912f00-5f57-11eb-8a7d-7fd08a0806aa.png)
